language: node_js
node_js:
- 0.10.26
services:
  - mongodb
cache:
  directories:
    - node_modules
install: npm install --ignore-scripts
before_script:
- npm install -g gulp
script:
- npm test
deploy:
  provider: heroku
  strategy: git
  app:
    master: nattr
  api_key:
    secure: N7oqm+EPnAEdwzX9S8UE/rt6PQ54LwIp/Q10Eb/Ph7ZzGNQnEcrhvqLmrnwmDIRaTTPmR9DFaLUhmxQgcuqgbMDzUyJgDE7LYcDGtNar5TbaRiT7tpognWnLsHJ124OKsfIR1V/2P3kna8qkR2L/1odye56x4GbdwKYpZVtDwiI=
